### ISSUE TITLE
Searchable type label logic

### ISSUE THREAD

**Issue by lzrscg** [modularcloud/explorer#196]
<img width="653" alt="Screenshot 2023-10-24 at 5 28 35 PM" src="https://github.com/modularcloud/explorer/assets/84213303/42f45fc4-9d91-4937-a730-004a64486b3c">
<img width="570" alt="Screenshot 2023-10-24 at 5 28 57 PM" src="https://github.com/modularcloud/explorer/assets/84213303/0544be9d-3800-45f6-8685-672607a492e4">
<img width="944" alt="Screenshot 2023-10-24 at 5 30 30 PM" src="https://github.com/modularcloud/explorer/assets/84213303/1ea55dfc-0de9-43cf-893b-f263114d5bc4">

Taking the second segment of the URL params and removing the `s` at the end does not always give the right conclusion. The page metadata could actually work as a good solution for determining the text that goes in the search bar. Or perhaps the `Page` schema should be updated to specifically contain a search bar value.

The modal can actually get the proper type name from the SearchBuilders, along with the path.

**Comment by fredk3** [comment]
## Ok some explications : 

1. there is a little delay because that's the time it takes for next to send a request to the server and get the result back, we have things in place to  make this faster, but a server-client communication is always subject to some delays

2. This second page is actually nextjs fault, when using redirect it always show a blank page before redirecting to the correct page (whether redirecting from a server or client component) https://user-images.githubusercontent.com/84213303/277859500-217577f2-74f5-4536-9990-2ed4e032b53f.png , the header skeleton is just because i added a condition to show a skeleton on search page ([https://github.com/modularcloud/explorer/blob/5aa992ad2dadd33bd66ad64e0604ee918101[…]53/apps/web/app/(entity)/%5Bnetwork%5D/%5B...path%5D/layout.tsx](https://github.com/modularcloud/explorer/blob/5aa992ad2dadd33bd66ad64e0604ee9181012253/apps/web/app/(entity)/%5Bnetwork%5D/%5B...path%5D/layout.tsx#L22-L24))

## And some ideas :

1. We can listen for navigations in the client with `useTransition`, but that'd need to be forwarded to a parent component (at the root of the layout even) that can listen with context (or something like that) and display a skeleton whenever it is notified to navigate and call `router.push(`/search/<something>`)` within a transition, it would be something like this : 

```tsx
// this is just the general outline, not the real code
import * as React from 'react';

export function ParentComponent() {
   const [isNavigating, startTransition] = React.useTransition();

   const onNavigate = (route: string) => startTransition(() => router.push(`/search/${route}`));
   
   if (isNavigating) {
    return <Skeleton />
   }

   return <>{/* children... */}</>
}
``` 

2. For the search redirect, i am thinking of maybe just rendering the content as the skeleton and then on the client, within a useEffect, calling router.push with the resolved route. router.push doesn't suffer from showing a blank page.

**Comment by fredk3** [comment]
The solution is to match the route client side, that could be reused by both the search modal and the search button.

**Comment by Fredkiss3** [comment]
already fixed.
