### ISSUE TITLE
Delayed navigation

### ISSUE THREAD

**Issue by lzrscg** [modularcloud/explorer#198]
This is a common issue in NextJS. But here is an important example that needs to be resolved.

User starts off on a page
<img width="1313" alt="Screenshot 2023-10-24 at 7 58 15 PM" src="https://github.com/modularcloud/explorer/assets/84213303/3ae5514e-4b58-479b-be3b-7499f0fe6698">

User searches for a new page
<img width="1301" alt="Screenshot 2023-10-24 at 7 55 34 PM" src="https://github.com/modularcloud/explorer/assets/84213303/f2242902-9d4b-414b-882f-b1d03fb90dc4">

**THE MAIN PROBLEM:** Modal closes with no indication of loading, even though the user took a search action (this is the original page we started at on). There should be an instant indication of loading a new page.
<img width="1306" alt="Screenshot 2023-10-24 at 7 56 23 PM" src="https://github.com/modularcloud/explorer/assets/84213303/cad20206-a791-429a-a24d-27bb97317c2e">

Then the loading state shows (**side note: we need to finish the side bar loading state styling**)
<img width="1313" alt="Screenshot 2023-10-24 at 7 57 07 PM" src="https://github.com/modularcloud/explorer/assets/84213303/312f32f1-88f0-40ce-b34f-acbd180fc43e">

I wonder if this is intentional? Did the page finish loading but the header and sidebar not?
<img width="1309" alt="Screenshot 2023-10-24 at 7 57 27 PM" src="https://github.com/modularcloud/explorer/assets/84213303/217577f2-74f5-4536-9990-2ed4e032b53f">

Then the next page finally loads
<img width="1302" alt="Screenshot 2023-10-24 at 7 55 59 PM" src="https://github.com/modularcloud/explorer/assets/84213303/d682f434-ca57-447d-91ea-36c51b3dde1d">

Full video:
https://github.com/modularcloud/explorer/assets/84213303/f39fb790-90b9-4ae9-b7c0-9edbaed6e3d9

**Comment by fredk3** [comment]
## Ok some explications : 

1. there is a little delay because that's the time it takes for next to send a request to the server and get the result back, we have things in place to  make this faster, but a server-client communication is always subject to some delays

2. This second page is actually nextjs fault, when using redirect it always show a blank page before redirecting to the correct page (whether redirecting from a server or client component) https://user-images.githubusercontent.com/84213303/277859500-217577f2-74f5-4536-9990-2ed4e032b53f.png , the header skeleton is just because i added a condition to show a skeleton on search page ([https://github.com/modularcloud/explorer/blob/5aa992ad2dadd33bd66ad64e0604ee918101[…]53/apps/web/app/(entity)/%5Bnetwork%5D/%5B...path%5D/layout.tsx](https://github.com/modularcloud/explorer/blob/5aa992ad2dadd33bd66ad64e0604ee9181012253/apps/web/app/(entity)/%5Bnetwork%5D/%5B...path%5D/layout.tsx#L22-L24))

## And some ideas :

1. We can listen for navigations in the client with `useTransition`, but that'd need to be forwarded to a parent component (at the root of the layout even) that can listen with context (or something like that) and display a skeleton whenever it is notified to navigate and call `router.push(`/search/<something>`)` within a transition, it would be something like this : 

```tsx
// this is just the general outline, not the real code
import * as React from 'react';

export function ParentComponent() {
   const [isNavigating, startTransition] = React.useTransition();

   const onNavigate = (route: string) => startTransition(() => router.push(`/search/${route}`));
   
   if (isNavigating) {
    return <Skeleton />
   }

   return <>{/* children... */}</>
}
``` 

2. For the search redirect, i am thinking of maybe just rendering the content as the skeleton and then on the client, within a useEffect, calling router.push with the resolved route. router.push doesn't suffer from showing a blank page.
